# Generated by Django 4.1.4 on 2022-12-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_pic',
            field=models.ImageField(blank=True, upload_to='artists'),
        ),
    ]
